package ast;

public enum TipoE {
  SUMA, RESTA, MUL, DIV, MOD, ENT, INCR, DECR, NOT, IGUAL, DISTINTO, AND, OR, MENOR, MENORIGUAL, MAYOR, MAYORIGUAL,
  LISTINST, FIN, INICIOFOR, FOR, IDEN, BOOL, CHAR, BIN, ASIGNA, WHILE, IF, ELIF, ELSE, PRINT, READ, FUNCION, ARGS,
  PROGRAMA, CSTRUCT, CARRAY, COLECCION, ARRAY, TAMARRAY, ACCESOARRAY, CAMPOS, STRUCT, TARRAY, TENT, TBOOL, TCHAR, TBIN,
  DECLARAFUNC, ARGSDEF, ENUMERADO, ENUMERADOS, DECLARAENUM, DECLARASTRUCT, ASIGNASTRUCT, ASIGNAARRAY, DECLARACION,
  DECLARABASICO, CONSTANTE
}
